// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Review2.Models;

namespace Review2.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20200220115513_reviewMigration4")]
    partial class reviewMigration4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Review2.Models.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Review")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Yellow fruit-eating monster",
                            Image = "/img/pacman.jpg",
                            Name = "Pac-Man",
                            Review = "I bought this arcade game, now I hate ghosts!",
                            ReviewId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Save the Realms from certain doom",
                            Image = "/img/GauntletLegends.jpg",
                            Name = "Gauntlet Legends",
                            Review = "Wtf I love this game?",
                            ReviewId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Dig and dug",
                            Image = "/img/digdug.jpg",
                            Name = "DigDug",
                            Review = "Being inflated till you explode has got to hurt!",
                            ReviewId = 3
                        });
                });

            modelBuilder.Entity("Review2.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "hlkjhlkjhkjlh",
                            Name = "ghassan"
                        },
                        new
                        {
                            Id = 2,
                            Description = "hlkjhlkjhkjlh",
                            Name = "ghassan"
                        },
                        new
                        {
                            Id = 3,
                            Description = "nbgkljglkjghlkjhl",
                            Name = "ali"
                        });
                });

            modelBuilder.Entity("Review2.Models.ProductModel", b =>
                {
                    b.HasOne("Review2.Models.Review", "ReviewPro")
                        .WithMany("Product")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
